name: CodeNotary verification

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
     - name: Checkout
       uses: actions/checkout@v1
     
     - name: Verify
       uses: vchain-us/verify-action@master
